package Payment;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PaymentTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.edge.driver", "D:\\Capgemini\\Softwares\\edgedriver_win64\\msedgedriver.exe");
    driver = new EdgeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void payment() {
    driver.get("https://www.universalclass.com/");
    driver.manage().window().maximize();
    driver.findElement(By.className("dropbtn")).click();
    driver.findElement(By.xpath("//a[contains(@href, \'https://members.universalclass.com/login.htm\')]")).click();
    driver.findElement(By.name("username")).sendKeys("Jogeshkumar184@gmail.com");
    driver.findElement(By.name("password")).sendKeys("jogesh1998");
//    driver.findElement(By.cssSelector("#LoginForm2020 > div:nth-child(5)")).click();
    driver.findElement(By.name("SubmitButton")).click();
    driver.findElement(By.id("clssicon")).click();
    driver.findElement(By.xpath("//button[@id=\'clssicon\']/img")).click();
    driver.findElement(By.xpath("(//button[@type=\'button\'])[4]")).click();
    driver.findElement(By.xpath("//div[@id=\'frontdropmaincontent\']/div[2]/div[3]/ul/li[2]/a/span")).click();
    driver.findElement(By.xpath("//img[@alt=\'Healing Affirmations\']")).click();
    driver.findElement(By.name("JoinClassButton1")).click();
    driver.findElement(By.linkText("Add to Cart")).click();
    driver.findElement(By.name("ContinueSubmit")).click();
    driver.findElement(By.id("first_name")).sendKeys("Jogesh ");
    driver.findElement(By.id("last_name")).sendKeys("Kumar");
    driver.findElement(By.id("address1")).sendKeys("Rewari");
    driver.findElement(By.id("city")).sendKeys("Rewari");
    driver.findElement(By.id("zip")).sendKeys("123401");
    {
      WebElement dropdown = driver.findElement(By.id("country"));
      dropdown.findElement(By.xpath("//option[. = 'India']")).click();
    }
    driver.findElement(By.id("ani")).sendKeys("8006464789");
    {
      WebElement dropdown = driver.findElement(By.id("state"));
      dropdown.findElement(By.xpath("//option[. = 'Alaska']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.id("cctype"));
      dropdown.findElement(By.xpath("//option[. = 'Visa']")).click();
    }
    driver.findElement(By.id("cc")).sendKeys("1234123412341234");
    {
      WebElement dropdown = driver.findElement(By.id("exp_month"));
      dropdown.findElement(By.xpath("//option[. = '11']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.id("exp_year"));
      dropdown.findElement(By.xpath("//option[. = '2038']")).click();
    }
    driver.findElement(By.id("sec")).sendKeys("231");
    driver.findElement(By.name("submitButton")).click();
    driver.findElement(By.xpath("//button[@id=\'frontdropclosebutton\']/span[2]")).click();
    driver.close();
  }
}
